---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update package index
      package:
        update_cache: true
      changed_when: false # Don't list as a changed

    - name: Upgrade all packages (RedHat based)
      dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Upgrade all packages (Deb based)
      apt:
        upgrade: yes
        update_cache: true
      when: ansible_os_family == "Debian"


  tasks:
    - name: install avahi for mDNS configurations (RedHat based)
      package:
        name: avahi
        state: latest
      when: ansible_os_family == "RedHat"

    - name: install avahi for mDNS configurations (Deb based)
      package:
        name: avahi-daemon
        state: latest
      when: ansible_os_family == "Debian"

