---
- hosts: localhost
  connection: local
  become: true


  pre_tasks:
    - name: update package index
      package:
        update_cache: true
      changed_when: false # Don't list as a changed


    - name: Upgrade all packages (RedHat based)
      dnf:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"


    - name: Upgrade all packages (Deb based)
      apt:
        upgrade: 'yes'
      when: ansible_os_family == "Debian"


  # TODO: Include in bootstrap role
  tasks:
    vars:
      ansible_user_name: "ansiblebot"

    - name: install avahi for mDNS configurations (RedHat based)
      package:
        name: avahi
        state: latest
      when: ansible_os_family == "RedHat"


    - name: install avahi for mDNS configurations (Deb based)
      package:
        name: avahi-daemon
        state: latest
      when: ansible_os_family == "Debian"


    - name: Create ansible user
      user:
        name: "{{ ansible_user_name }}"
        system: true
        state: present
        password: '!' # disable password
        groups: root


    # TODO: Move key to a dedicated file.
    - name: Add public ssh key for ansible user
        authorized_keys:  
          user: "{{ ansible_user_name }}"
          state: present
          key: >
            ssh-ed25519
            AAAAC3NzaC1lZDI1NTE5AAAAIDcfhe0usxzgCZKkY54t2YH9aViT5am+dypn2aNP/5SV
            Ansiblebot Sept 2023

    - name: Add ansible role to sudoers list
       src: sudoer_ansiblebot 
       dest: "/etc/sudoers.d/{{ ansible_user_name }}"
       owner: root
       group: root
       mode: 0440



