---
# ansible-pull --ask-become-pass -U git@github.com:maubuz/ansible-homelab.git workstation.yml

- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install workstation packages (all linux families)
      package:
        update_cache: true
        name:
          - input-remapper
          - gimp
          - inkscape
          - vim
        state: latest

    - name: Install gnome specific packaes (RedHat based)
      package:
        name:
          - gnome-pomodoro
        state: latest
      when: ansible_os_family == "RedHat"


    - name: Install gnome specific packaes (Deb based)
      package:
        name:
          - gnome-shell-pomodoro
        state: latest
      when: ansible_os_family == "Debian"
