---
# ansible-pull --ask-become-pass -U git@github.com:maubuz/ansible-homelab.git workstation.yml

- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install workstation packages (all linux families)
      package:
        update_cache: true
        name:
          - input-remapper
          - gimp
          - inkscape
          - vim
          - fd-find
          - git-delta
          - fzf
          - bat
        state: latest

    - name: Install gnome specific packaes (RedHat based)
      package:
        name:
          - gnome-pomodoro
        state: latest
      when: ansible_os_family == "RedHat"


    - name: Install gnome specific packaes (Deb based)
      package:
        name:
          - gnome-shell-pomodoro
          - gnome-tweaks
        state: latest
      when: ansible_os_family == "Debian"


    - name: Install snap packages with sandbox (Ubuntu)
      community.general.snap:
        name:
          - chromium
          - chromium-ffmpeg
          - logseq
      when: ansible_facts['distribution'] == "Ubuntu"
      
    - name: Install snap packages w/ "classic" privige (Ubuntu)
      community.general.snap:
        name:
          - nvim
        classic: true
      when: ansible_facts['distribution'] == "Ubuntu"


    - name: Install Syncthing
      package:
        name: syncthing
        state: latest

    - name: Enable Syncthing
      ansible.builtin.systemd_service:
        name: syncthing
        enabled: true
        scope: user
        state: started

    - name: Start Syncthing
      ansible.builtin.systemd_service:
        name: syncthing
        scope: user
        state: started

