---
# Run as github pull:
# ansible-pull --ask-become-pass -U git@github.com:maubuz/ansible-homelab.git workstation.yml

# Run locally:
# ansible-playbook --ask-become <playbook-name.yml>

- hosts: localhost
  connection: local
  become: true
  tasks:

    - name: Install Syncthing
      package:
        name: syncthing
        state: latest

    - name: Enable Syncthing
      ansible.builtin.systemd_service:
        name: syncthing
        scope: user
        enabled: true
        state: started
        daemon_reload: true
      become_user: mau
      become: no

    # - name: Start Syncthing
    #   ansible.builtin.systemd_service:
    #     name: syncthing
    #     scope: user
    #     state: started
    #   become_user: mau
    #   become: no
    #
