---
# ansible-pull --ask-become-pass -U git@github.com:maubuz/ansible-homelab.git workstation.yml

- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Install python requirements for gnome extensions
      package:
        update_cache: true
        name:
          - python3-pip
          - pipx
        state: latest
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Ensure pipx is in path
      ansible.builtin.command:
        cmd: pipx ensurepath
      become_user: mau

    # See https://github.com/essembeh/gnome-extensions-cli
    - name: Install gnome-extension-cli
      community.general.pipx:
        name: gnome-extensions-cli
        executable: /usr/bin/pipx 
        state: latest
        system_site_packages: true
      become_user: mau

    - name: Install gnome extensions with gnome-extension-cli
      ansible.builtin.command:
        # Installing extensions:
        # https://github.com/MajortomVR/simple-timer-extension
        # https://github.com/corecoding/Vitals
        cmd: gext install simple-timer@majortomvr.github.com system-monitor-next@paradoxxx.zero.gmail.com just-perfection-desktop@just-perfection
      become_user: mau
